import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
function client(){const status={textContent:''};const context=vm.createContext({structuredClone,setTimeout:()=>0,clearTimeout:()=>{},document:{getElementById:()=>status}});const start=html.indexOf('const cloud='),end=html.indexOf('if(!await cloud.init())');vm.runInContext(html.slice(start,end)+'\nglobalThis.client=cloud;',context);return {cloud:context.client,status};}
test('target identity comes from the verified member',()=>{const {cloud}=client();cloud.member={userId:'U2'};cloud.data={bdm_active_user:'U1'};assert.equal(cloud.get('bdm_active_user',null),'U2');});
test('conflicting writes stay pending and cannot be overwritten',async()=>{const {cloud,status}=client();cloud.data={bdm_leads:[{id:'L1'}]};cloud.pending=true;cloud.request=async()=>{const e=Error('Conflict');e.status=409;throw e;};await assert.rejects(cloud.flush());assert.equal(cloud.blocked,true);assert.equal(cloud.pending,true);assert.match(status.textContent,/NOT saved/);assert.equal(cloud.data.bdm_leads[0].id,'L1');assert.throws(()=>cloud.set('bdm_leads',[]));});
test('temporary network errors permit retry and retain data',async()=>{const {cloud}=client();cloud.pending=true;cloud.data={bdm_activity:[]};cloud.request=async()=>{throw Error('Offline');};await assert.rejects(cloud.flush());assert.equal(cloud.blocked,false);assert.equal(cloud.pending,true);cloud.request=async()=>({revision:2});await cloud.flush();assert.equal(cloud.pending,false);assert.equal(cloud.revision,2);});
test('changes made during a save wait for its revision',async()=>{const {cloud}=client();let resolve;const calls=[];cloud.pending=true;cloud.data={bdm_leads:[{id:'first'}]};cloud.request=async(method,body)=>{calls.push(body);if(calls.length===1)return new Promise(r=>resolve=r);return {revision:2};};const saving=cloud.flush();cloud.set('bdm_leads',[{id:'second'}]);resolve({revision:1});await saving;assert.equal(calls.length,2);assert.equal(calls[0].revision,0);assert.equal(calls[1].revision,1);assert.equal(calls[1].data.bdm_leads[0].id,'second');});
